permalink: /:title
pygments: true
markdown: kramdown

toc:
  - head: '/index.html'
    body: []

  # - head: '/dashboard/index.html'
  #   body: []

  - head: '/about/index.html'
    body:
     - '/about/features.html'
     - '/about/gettingstarted.html'
     - '/about/accounts.html'

  - head: '/publish/index.html'
    body:
     - /publish/prepare.html
     - /publish/upload.html

  - head: '/maintain/index.html'
    body: 
     - /maintain/view.html
     - /maintain/update.html
     - /maintain/share.html

  - head: '/use/index.html'
    body: 
      - /use/download.html
      - /use/api.html
      - /use/widgets.html
  - head: '/support/index.html'
    body: 
      - '/support/faq.html'
      - '/support/contact.html'
      - '/support/roadmap.html'